apiVersion: v1
kind: Service
metadata:
  name: go-service
  labels:
    app: go-service
    service: go-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: go-service
  type: ClusterIP
